### ISSUE TITLE
Not a program account error

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1050]
```
INFO 2024-01-02T06:37:27.746974415Z [06:37:27.638] ERROR (sendTransactionDelegatedFee/40): Returned error: not a program account (e.g., an account having code and storage)
INFO 2024-01-02T06:37:27.747015919Z file: "file:///app/dist/reporter/utils.js"
INFO 2024-01-02T06:37:27.747024902Z err: {
INFO 2024-01-02T06:37:27.747029804Z "type": "Error",
INFO 2024-01-02T06:37:27.747034294Z "message": "Returned error: not a program account (e.g., an account having code and storage)",
INFO 2024-01-02T06:37:27.747038379Z "stack":
INFO 2024-01-02T06:37:27.747042257Z Error: Returned error: not a program account (e.g., an account having code and storage) at Object.ErrorResponse (/app/node_modules/caver-js/packages/caver-core-helpers/src/errors.js:85:16) at /app/node_modules/caver-js/packages/caver-core-requestmanager/src/index.js:155:44 at /app/node_modules/caver-js/packages/caver-core-requestmanager/caver-providers-http/src/index.js:153:17 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
INFO 2024-01-02T06:37:27.747062179Z }
```

**Comment by nick-bisonai** [comment]
This used to happen from onchain aggregator, now that onchain aggregation is deprecated, will reopen if it occurs again
