### ISSUE TITLE
vrf test failure

### ISSUE THREAD

**Issue by nick-bisonai** [Bisonai/orakl#1299]
```
829 passing (55s)
  4 failing

  1) VRF internal aux. functions:
       should verify an ecMul operation (ecrecover hack) (1):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/vrf/VRFInternal.test.cjs:88:25)

  2) VRF internal aux. functions:
       should verify an ecMul operation (ecrecover hack) (2):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/vrf/VRFInternal.test.cjs:88:25)

  3) VRF internal aux. functions:
       should verify an ecMul operation (ecrecover hack) (3):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/vrf/VRFInternal.test.cjs:88:25)

  4) Proof verification functions:
       should fast verify a VRF proof (1):

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/vrf/VRF.test.cjs:152:28)
```

**Comment by Intizar-T** [comment]
all tests passing both locally and in github actions: https://github.com/Bisonai/orakl/actions/runs/9561882181/job/26357066272
