### ISSUE TITLE
Reporter pod restarts

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#477]
Report from @joseph-bisonai below:

Reporter pod restart with error.

Even though there is error pod should not restart. I think somewhere we need to catch the error.

`Error: bad response (status=502, headers={"server":"awselb/2.0","date":"Tue, 28 Mar 2023 04:01:40 GMT","content-type":"text/html","content-length":"122","connection":"close","set-cookie":"AWSALB=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/, AWSALBCORS=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/; SameSite=None; Secure"}, body="<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n", requestBody="{\"method\":\"eth_getTransactionByHash\",\"params\":[\"0x3d78a2ccfaa9d64a9fc0e960a34c4acdeebe6b6c4b2f8d10bcc38609991bc88f\"],\"id\":91848,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://api.baobab.klaytn.net:8651", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /app/node_modules/@ethersproject/web/lib/index.js:275:36
    at step (/app/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/app/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/app/node_modules/@ethersproject/web/lib/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'bad response',
  code: 'SERVER_ERROR',
  status: 502,
  headers: {
    server: 'awselb/2.0',
    date: 'Tue, 28 Mar 2023 04:01:40 GMT',
    'content-type': 'text/html',
    'content-length': '122',
    connection: 'close',
    'set-cookie': 'AWSALB=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/, AWSALBCORS=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/; SameSite=None; Secure'
  },
  body: '<html>\r\n' +
    '<head><title>502 Bad Gateway</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>502 Bad Gateway</h1></center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  requestBody: '{"method":"eth_getTransactionByHash","params":["0x3d78a2ccfaa9d64a9fc0e960a34c4acdeebe6b6c4b2f8d10bcc38609991bc88f"],"id":91848,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://api.baobab.klaytn.net:8651'
}`

**Comment by martinkersner** [comment]
Related thread https://bisonai.slack.com/archives/C04772WQ3DW/p1680592375090989

The pod that restarts is `agregator-worker`.

Updated formatting which shows that the problem is not related to axios.

```
Error: bad response status=502
code=SERVER_ERROR, version=web/5.7.1
```

Headers
```
{
  "server": "awselb/2.0",
  "date": "Tue, 28 Mar 2023 04:01:40 GMT",
  "content-type": "text/html",
  "content-length": "122",
  "connection": "close",
  "set-cookie": "AWSALB=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/, AWSALBCORS=3doaabt3KaMHNR4dZVfSXPwUJcndMEwEDQ1BBsXvlpjUnUL4GO8p0czEVGuFM+eI07K8K3IiPDUhgrz4HEkr+ayhtRUozq7wKLy1I4qSiinOKW0P2shVdLBk3L+o; Expires=Tue, 04 Apr 2023 04:01:40 GMT; Path=/; SameSite=None; Secure"
}
```

Body
```
"<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n", requestBody="{\"method\":\"eth_getTransactionByHash\",\"params\":[\"0x3d78a2ccfaa9d64a9fc0e960a34c4acdeebe6b6c4b2f8d10bcc38609991bc88f\"],\"id\":91848,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://api.baobab.klaytn.net:8651"
```

**Comment by martinkersner** [comment]
Closing down! The issue did not appear since we started using our own JSON-RPC nodes.
