### ISSUE TITLE
Deactivate is not working for aggregator.

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#940]
When we try to stop aggregator by deactivating it trough cli, the heartbeat queue job is stay in queue and makes issue.

**Comment by nick-bisonai** [comment]
### error message is as followed
```bash
AggregatorNotFoundInState
    at State.updateTimestamp (file:///app/dist/worker/state.js:122:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Worker.wrapper [as processFn] (file:///app/dist/worker/data-feed.js:212:9)
    at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:339:28)
    at async Worker.retryIfFailed (/app/node_modules/bullmq/dist/cjs/classes/worker.js:513:24)
```

### error location is as followed

1. core/src/worker/data-feed.ts 

`await state.updateTimestamp(oracleAddress)`

https://github.com/Bisonai/orakl/blob/7a54ae755d2054bcdac1a552aa3b3af8bfb13adb/core/src/worker/data-feed.ts#L409

2. core/src/worker/state.ts

`async updateTimestamp()` -> line 216 `throw new OraklError(OraklErrorCode.AggregatorNotFoundInState)`

https://github.com/Bisonai/orakl/blob/7a54ae755d2054bcdac1a552aa3b3af8bfb13adb/core/src/worker/state.ts#L216


### suggestion

- adding oracle state check from submitHeartbeatJob?

```
if(!await state.isActive(oracleAddress)){
 job.remove();
 return;
}
```

**Comment by nick-bisonai** [comment]
@martinkersner 
I'm not sure, maybe the removal function is not removing all the related jobs. just removing aggregator from the activeAggregators

```
/**
   * Remove aggregator given `aggregatorHash`. Aggregator can be removed only if
   * it was in an active state.
   *
   * @param {string} aggregator hash
   * @exception {OraklErrorCode.AggregatorNotRemoved} raise when no reporter was removed
   */
  async remove(aggregatorHash: string) {
    this.logger.debug('remove')

    const activeAggregators = await this.active()
    const numActiveAggregators = activeAggregators.length

    const index = activeAggregators.findIndex((L) => L.aggregatorHash == aggregatorHash)
    if (index === -1) {
      const msg = `Aggregator with aggregatorHash=${aggregatorHash} was not found.`
      this.logger.debug({ name: 'remove', file: FILE_NAME }, msg)
      throw new OraklError(OraklErrorCode.AggregatorNotFoundInState, msg)
    }

    const removedAggregator = activeAggregators.splice(index, 1)[0]

    const numUpdatedActiveAggregators = activeAggregators.length
    if (numActiveAggregators == numUpdatedActiveAggregators) {
      const msg = `Aggregator with aggregatorHash=${aggregatorHash} was not removed. Aggregator was not found.`
      this.logger.debug({ name: 'remove', file: FILE_NAME }, msg)
      throw new OraklError(OraklErrorCode.AggregatorNotRemoved, msg)
    }

    // Update active aggregators
    await this.redisClient.set(this.stateName, JSON.stringify(activeAggregators))

    return removedAggregator
  }
```

**Comment by nick-bisonai** [comment]
should this kind of code be added to remove jobs from queue?

```
    const allHeartbeatJobs = await this.heartbeatQueue.getJobs();

    allHeartbeatJobs
      .filter(job => job.data.oracleAddress == oracleAddress)
      .forEach(job => job.remove())

    const allSubmitHeartbeatJobs = await this.submitHeartbeatQueue.getJobs();

    allSubmitHeartbeatJobs
      .filter(job => job.data.oracleAddress == oracleAddress)
      .forEach(job => job.remove())

```

**Comment by nick-bisonai** [comment]
conclusion: `checkHeartbeatQueue` should be cleared on aggregator deactivation. since jobs in `checkHeartbeatQueue` repeatedly adds job into `submitHeartbeatQueue` it should definitely be the reason for `AggregatorNotFoundInState` error inside `submitHeartbeatJob` being repeated.

**Comment by nick-bisonai** [comment]
I have found following code from `checkHeartbeatJob`
`activeAggregators = await state.active()`

https://github.com/Bisonai/orakl/blob/985aa5f188f242da72648d6a201ff8d0872e5d9c/core/src/worker/data-feed.ts#L430-L432

then it shouldn't add job with deactivated aggregator into `submitHeartbeatQueue`. Then again, I wonder why this error happened 🤔

**Comment by nick-bisonai** [comment]
now I'm starting to think that `aggregatorJob` could be a problem
it also adds job into `submitHeartbeatQueue`

https://github.com/Bisonai/orakl/blob/7a54ae755d2054bcdac1a552aa3b3af8bfb13adb/core/src/worker/data-feed.ts#L203

and `SUBMIT_HEARTBEAT_QUEUE_SETTINGS` is as followed

https://github.com/Bisonai/orakl/blob/7a54ae755d2054bcdac1a552aa3b3af8bfb13adb/core/src/settings.ts#L156-L161
it attempts 10 times on failure

maybe adding aggregator active check in `submitHeartbeatQueue` could help

**Comment by nick-bisonai** [comment]
Think I was right that the cause was coming from aggregatorJob

<img width="674" alt="image" src="https://github.com/Bisonai/orakl/assets/148735107/da113bc2-d975-4e2f-9d2e-706ef8860226">
job name is written as `aggregator-submission` which can be found only from
https://github.com/Bisonai/orakl/blob/985aa5f188f242da72648d6a201ff8d0872e5d9c/core/src/worker/data-feed.ts#L203-L205

**Comment by nick-bisonai** [comment]
aggregator queue is added in 2 places

1. `AggregatorQueue.add` happens in `heartbeatJob`, yet it checks if oracleAddress isActive so this is probably not the reason

https://github.com/Bisonai/orakl/blob/985aa5f188f242da72648d6a201ff8d0872e5d9c/core/src/worker/data-feed.ts#L342-L346

2. `workerQueue.add` happens also in `processEventJob` in `listener.ts`

https://github.com/Bisonai/orakl/blob/985aa5f188f242da72648d6a201ff8d0872e5d9c/core/src/listener/listener.ts#L350-L353

yet it doesn't check if the oracleAddress is active or not
adding statecheck in here might help

**Comment by nick-bisonai** [comment]
Another approach would be...
whenever `state.remove()` is called, iterate through all related queues and removing related jobs with deactivated aggregator

https://github.com/Bisonai/orakl/blob/985aa5f188f242da72648d6a201ff8d0872e5d9c/core/src/settings.ts#L93-L113
